spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  management:
    endpoints:
      web:
        exposure:
          include: health

#logging:
#  level:
#    root: DEBUG
#    org.springframework: DEBUG
 #   org.hibernate: DEBUG
 #   controllers: DEBUG
#    services: DEBUG 
#  file:
#    path: /var/log/myapp
 #   name: /var/log/myapp/application.log
 # pattern:
 #   file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
 #   console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
 # charset:
 #   file: UTF-8
 #   console: UTF-8

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_BUCKET_NAME}
  sns:
    topic:
      arn: ${AWS_SNS_TOPIC_ARN}

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}
  from:
    email: ${EMAIL_FROM}

metrics:
  statsd:
    host: localhost
    port: 8125
  prefix: csye6225


server:
  forward-headers-strategy: framework
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/myapp
      prefix: access
      suffix: .log
      file-date-format: yyyy-MM-dd
      pattern: '%d{[dd/MMM/yyyy:HH:mm:ss Z]} %h "%r" %s %b %D'
      rotate: true

jwt:
  secret: ${JWT_SECRET}