name: CI/CD Pipeline for Spring Boot Application
run-name: Worflow for Assignment 4 

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1  
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: webapp
  DB_PORT: 5432

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Application
        run: mvn clean package

      - name: Run Tests
        run: mvn test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Application
        run: mvn clean package

      - name: Prepare Application Artifact
        run: cp target/*.jar app.jar

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      - name: Build AMI with Packer
        run: |
          packer init packer-template.pkr.hcl
          packer validate packer-template.pkr.hcl
          packer build -var "db_user=${{ env.DB_USER }}" -var "db_password=${{ env.DB_PASSWORD }}" packer-template.pkr.hcl

      # Optional: Deploy infrastructure with Terraform
      # - name: Install Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: latest

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

