name: Packer Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Packer Template
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.8.7'

      - name: Verify Packer
        id: packer-verify
        run: |
          packer fmt -check packer-webapp.pkr.hcl
          packer validate packer-webapp.pkr.hcl