name: Packer Validation
run-name: "PR #${{ github.event.number }} - Validate Packer Configuration"

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Packer
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.8.7'

      - name: Verify Packer
        run: |
          packer fmt -check packer-webapp.pkr.hcl
          packer validate -syntax-only packer-webapp.pkr.hcl